### ISSUE TITLE
Async actor function?

### ISSUE THREAD

**Issue by yiv** [hominee/crossbus#1]

**Comment by hominee** [comment]
the short answer is yes, crossbus supports future routine. but to put it more precisely,  crossbus follows a similar pattern to deal with future as actix/ yew.  if you wanna run a async function
```rust
async fn run() {
    // do stuff here
}
```
you can 
- convert it into [actor future](https://docs.rs/crossbus/latest/crossbus/actor/trait.Future.html) with [Localizer](https://docs.rs/crossbus/latest/crossbus/actor/struct.Localizer.html) then spawn it with [Context::spawn](https://docs.rs/crossbus/latest/crossbus/context/struct.Context.html#method.spawn)
- or more directly, use [Context::send_future](https://docs.rs/crossbus/latest/crossbus/context/struct.Context.html#method.send_future)

for a more general type like `Stream`, `Message Stream`, `Delayed Timer` or `Blocking wait (sleep)`,
crossbus has straight support for them, you can just follow [the document](https://docs.rs/crossbus) or see [the 
integration tests](https://github.com/hominee/crossbus/tree/master/tests) as a reference
