### ISSUE TITLE
support virtual actor model?

### ISSUE THREAD

**Issue by Cloud33** [hominee/crossbus#2]
like [orleans](https://github.com/dotnet/orleans), This concept is very easy to accept and learn.

**Comment by hominee** [comment]
As a actor computing model, crossbus supports in-memory actor clusters computation and interaction. when an actor gets started, it can make local decisions, create more actors, send more messages, and determine how to respond to the next message received. or to put it in short, an actor can update its inner state or change others' via messages.

if you wanna make an comparison with other similar framework, eg. `actix`, `orleans`,  there are some differences based what I know:
- `Actix` is mature rust actor framework, which based Tokio runtime, and has developed a stable and rich ecosystem, like `actix-web`, `actix-net` etc.  crossbus take a similar design of Actix but extends it to a lower level with more compatibility, right now, crossbus can almost fulfill what actix does except for actor isolation.
- orleans is cloud .net actor framework, designed for distributed cloud computing. in procession of some good features like runtime-isolation, beyond in-memory to perpetual physical existence, distributive scaling what are good inspirations for crossbus' future development.

**Comment by Cloud33** [comment]
Yes, I really like it, but I haven't found a similar framework in Rsut. If Crossbus supports the virtual actor model, it would be great.
